version: "3.9"
services:
  db:
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD", "pg_isready"]
    image: "postgres:14-alpine"
    user: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "6432:5432" # Avoid conflict with other dbs
  dialog:
    build:
      context: .
      dockerfile: dockerfiles/dialog.Dockerfile
    environment:
      AUTH_KEY: /etc/perms.pub.pem
      HTTPS_CERT_FULLCHAIN: /etc/ssl/fullchain.pem
      HTTPS_CERT_PRIVKEY: /etc/ssl/privkey.pem
      INTERACTIVE: "false"
    ports:
      - "4443:4443"
    volumes:
      - dialog:/code
    working_dir: /code
  reticulum:
    build:
      context: ./services/reticulum
      dockerfile: TurkeyDockerfile
      target: dev
    depends_on:
      - db
    environment:
      DB_CREDENTIALS: postgres
      DB_HOST: db
      DIALOG_HOSTNAME: "hubs.local"
      DIALOG_PORT: 4443
      HUBS_ADMIN_INTERNAL_HOSTNAME: hubs-admin
      HUBS_CLIENT_INTERNAL_HOSTNAME: hubs-client
      POSTGREST_INTERNAL_HOSTNAME: postgrest
      SPOKE_INTERNAL_HOSTNAME: spoke
    ports:
      - "4000:4000"
    volumes:
      - reticulum:/code
      - retstorage:/code/storage/dev
networks:
  default:
    name: mozilla-hubs-lite
volumes:
  dialog:
  pgdata:
  reticulum:
  retstorage:
x-mutagen:
  sync:
    defaults:
      ignore:
        paths:
          - ".DS_Store"
          - ".gitignore"
          - "/certs/"
          - "/node_modules/"
          - "package-lock.sha512"
        vcs: true
      mode: "two-way-resolved"
    dialog:
      alpha: ./services/dialog
      beta: "volume://dialog"
    reticulum:
      alpha: ./services/reticulum
      beta: "volume://reticulum"
      ignore:
        paths:
          - "/_build/"
          - "/bin/"
          - "/storage/"
